version: '3'
services:
  db:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: any
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/override.cnf:/etc/mysql/conf.d/override.cnf

  static:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-files:/app/static

  web:
    image: test
    restart: unless-stopped
    environment:
      DB_PASSWORD: password
      DJANGO_SECRET_KEY: SecretString
      DJANGO_CONFIGURATION: Stage
      SITE_URL: http://127.0.0.1:8001
      FACEBOOK_KEY:
      FACEBOOK_SECRET:
    ports:
      - 8001:8000
    depends_on:
      - db
    volumes:
      - ./.env:/app/src/.env
      - static-files:/app/static

volumes:
  db-data:
  static-files:

